# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Corte Suprema'), (2, 'Corte Apelaciones'), (3, 'Civil'), (4, 'Laboral'), (5, 'Penal'), (6, 'Cobranza'), (7, 'Familia')])),
                ('archived', models.BooleanField(default=False)),
                ('caratulado', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocApelaciones',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('salas', models.TextField(blank=True, null=True)),
                ('foja_inicial', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='DocCivil',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etapa', models.TextField(blank=True, null=True)),
                ('tramite', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('foja', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='DocCobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.TextField(blank=True, null=True)),
                ('tramite', models.TextField(blank=True, null=True)),
                ('desc_tramite', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='DocFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.TextField(blank=True, null=True)),
                ('tramite', models.TextField(blank=True, null=True)),
                ('desc_tramite', models.TextField(blank=True, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='DocLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(blank=True, null=True)),
                ('tramite', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='DocPenal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('cambio_estado', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='DocSuprema',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('anio', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('nomenclatura', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('salas', models.TextField(blank=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('initial_migration_done', models.BooleanField(default=False)),
                ('clave', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='causa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
    ]
