# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170319_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpenal',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
