# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170320_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccobranza',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docfamilia',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
