# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='docapelaciones',
            name='libro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docapelaciones',
            name='nro_ingreso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
