# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170331_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccivil',
            name='tribunal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
