# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_doccivil_tribunal'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpenal',
            name='tribunal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
