# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_docpenal_tribunal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscritoCivilPorResolver',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('solicitante', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Causa')),
            ],
            options={
                'verbose_name_plural': 'Escritos por resolver',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
